### ISSUE TITLE
What does Loading and Scripting refer to in the benchmarks?

### ISSUE THREAD

**Issue by elliotlings** [0x8890/simulacra#6]
What does Loading and Scripting refer to in the benchmarks?

Howcome innerHTML is slower?

Would love to know!

Thanks :-)

**Comment by 0x8890** [comment]
It's what is reported in the Chrome Devtools:

<img width="801" alt="screen shot 2015-11-21 at 10 34 57" src="https://cloud.githubusercontent.com/assets/1175095/11342397/8984731c-9207-11e5-885c-cd054aa82b74.png">
Left: React.js, right: Simulacra.js

`innerHTML` is slower because it has to parse a string and render it to the DOM on each iteration, though I admit it's a very naive implementation. [Here's what it looks like](https://github.com/0x8890/simulacra/blob/master/benchmark/naive_innerhtml.html).
